apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/coolapp-repo.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: coolapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

