apiVersion: v1
kind: Service
metadata:
  name: coolapp-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: coolapp
    # We'll update this label to switch between blue and green
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

