name: CoolApp CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          your-registry/coolapp:latest
          your-registry/coolapp:${{ github.sha }}
          your-registry/coolapp:blue
        build-args: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Update Kubernetes manifests
      run: |
        sed -i 's|your-registry/coolapp:blue|your-registry/coolapp:${{ github.sha }}|' k8s/deployment-blue.yaml
        sed -i 's|{{ .Values.buildDate }}|'$(date -u +'%Y-%m-%dT%H:%M:%SZ')'|' k8s/deployment-blue.yaml
        
    - name: Commit updated manifests
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/deployment-blue.yaml
        git commit -m "Update image tag and build date for blue deployment"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

